//===========================================================================
// 
// EconomyWar 4 Player v.1.8.5
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Tue May 14 16:59:30 2019
//   Map Author: RedConcrete
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // User-defined
    item                    udg_GetWood100             = null
    item                    udg_SellWood100            = null
    force                   udg_Spieler1               = null
    force                   udg_Spieler2               = null
    force                   udg_Spieler3               = null
    force                   udg_Spieler4               = null
    force                   udg_WTF                    = null

    // Generated
    rect                    gg_rct_Start               = null
    rect                    gg_rct_Player1             = null
    rect                    gg_rct_Player2             = null
    rect                    gg_rct_Playar3             = null
    rect                    gg_rct_Player4             = null
    rect                    gg_rct_Laufen2             = null
    camerasetup             gg_cam_Anfang2             = null
    camerasetup             gg_cam_Player1             = null
    camerasetup             gg_cam_Player2             = null
    camerasetup             gg_cam_Player3             = null
    camerasetup             gg_cam_Player4             = null
    string                  gg_snd_War3XMainScreen
    string                  gg_snd_UndeadX1
    string                  gg_snd_Undead1
    string                  gg_snd_Undead2
    string                  gg_snd_Undead3
    string                  gg_snd_Human1
    trigger                 gg_trg_SpielerGruppe       = null
    trigger                 gg_trg_Musik               = null
    trigger                 gg_trg_Verkaufen           = null
    trigger                 gg_trg_Gate_Open_player1_1 = null
    trigger                 gg_trg_Gate_Close_player1_1 = null
    trigger                 gg_trg_Gate_Open_player1_2 = null
    trigger                 gg_trg_Gate_Close_player1_2 = null
    trigger                 gg_trg_Gate_Open_player2_1 = null
    trigger                 gg_trg_Gate_Close_player2_1 = null
    trigger                 gg_trg_Gate_Open_player2_2 = null
    trigger                 gg_trg_Gate_Close_player2_2 = null
    trigger                 gg_trg_Gate_Open_player3_1 = null
    trigger                 gg_trg_Gate_Close_player3_1 = null
    trigger                 gg_trg_Gate_Open_player3_2 = null
    trigger                 gg_trg_Gate_Close_player3_2 = null
    trigger                 gg_trg_Gate_Open_player4_1 = null
    trigger                 gg_trg_Gate_Close_player4_1 = null
    trigger                 gg_trg_Gate_Open_player4_2 = null
    trigger                 gg_trg_Gate_Close_player4_2 = null
    trigger                 gg_trg_KameraIntro         = null
    trigger                 gg_trg_KameraZuerck        = null
    trigger                 gg_trg_StartGeld           = null
    trigger                 gg_trg_Pause               = null
    trigger                 gg_trg_Unpause             = null
    trigger                 gg_trg_AdminComand         = null
    trigger                 gg_trg_GeldBeute           = null
    trigger                 gg_trg_Building_Destroyed_Player1 = null
    trigger                 gg_trg_Building_Destroyed_Player2 = null
    trigger                 gg_trg_Building_Destroyed_Player3 = null
    trigger                 gg_trg_Building_Destroyed_Player4 = null
    trigger                 gg_trg_Building_Destroyed  = null
    trigger                 gg_trg_Check_if_Players_Leave = null
    trigger                 gg_trg_Check_if_Players_is_not_in_use = null
    trigger                 gg_trg_Sichtbar            = null
    trigger                 gg_trg_Winners_Declared    = null
    trigger                 gg_trg_AIStart             = null
    unit                    gg_unit_h000_0084          = null
    unit                    gg_unit_u000_0077          = null
    unit                    gg_unit_u000_0074          = null
    unit                    gg_unit_u000_0075          = null
    unit                    gg_unit_u000_0076          = null
    unit                    gg_unit_h000_0102          = null
    unit                    gg_unit_h00G_0100          = null
    unit                    gg_unit_h00G_0099          = null
    unit                    gg_unit_h000_0103          = null
    unit                    gg_unit_h000_0098          = null
    unit                    gg_unit_h00G_0101          = null
    unit                    gg_unit_h00G_0096          = null
    unit                    gg_unit_h00G_0097          = null
    unit                    gg_unit_h000_0085          = null
    unit                    gg_unit_h000_0086          = null
    unit                    gg_unit_h00G_0087          = null
    unit                    gg_unit_h000_0089          = null
    unit                    gg_unit_h000_0090          = null
    unit                    gg_unit_h00G_0091          = null
    destructable            gg_dest_B002_0198          = null
    destructable            gg_dest_B002_0188          = null
    destructable            gg_dest_B002_0187          = null
    destructable            gg_dest_B003_1355          = null
    destructable            gg_dest_B003_1350          = null
    destructable            gg_dest_B003_0201          = null
    destructable            gg_dest_B002_0200          = null
    destructable            gg_dest_B003_1349          = null
endglobals

function InitGlobals takes nothing returns nothing
    set udg_Spieler1 = bj_FORCE_PLAYER[0]
    set udg_Spieler2 = bj_FORCE_PLAYER[1]
    set udg_Spieler3 = bj_FORCE_PLAYER[2]
    set udg_Spieler4 = bj_FORCE_PLAYER[3]
    set udg_WTF = CreateForce()
endfunction

//***************************************************************************
//*
//*  Unit Item Tables
//*
//***************************************************************************

function Unit000108_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000109_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000110_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000111_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000112_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000113_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000114_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000115_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'tst2', 50 )
        call RandomDistAddItem( 'tstr', 50 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction


//***************************************************************************
//*
//*  Sounds
//*
//***************************************************************************

function InitSounds takes nothing returns nothing
    set gg_snd_War3XMainScreen = "Sound\\Music\\mp3Music\\War3XMainScreen.mp3"
    set gg_snd_UndeadX1 = "Sound\\Music\\mp3Music\\UndeadX1.mp3"
    set gg_snd_Undead1 = "Sound\\Music\\mp3Music\\Undead1.mp3"
    set gg_snd_Undead2 = "Sound\\Music\\mp3Music\\Undead2.mp3"
    set gg_snd_Undead3 = "Sound\\Music\\mp3Music\\Undead3.mp3"
    set gg_snd_Human1 = "Sound\\Music\\mp3Music\\Human1.mp3"
endfunction

//***************************************************************************
//*
//*  Destructable Objects
//*
//***************************************************************************

function CreateAllDestructables takes nothing returns nothing
    local destructable d
    local trigger t
    local real life
    set gg_dest_B002_0188 = CreateDestructable( 'B002', -3648.0, 704.0, 270.000, 0.900, 0 )
    set gg_dest_B002_0187 = CreateDestructable( 'B002', -1600.0, 704.0, 270.000, 0.900, 0 )
    set gg_dest_B002_0200 = CreateDestructable( 'B002', -1472.0, -3008.0, 270.000, 0.900, 0 )
    set gg_dest_B002_0198 = CreateDestructable( 'B002', -3648.0, -3008.0, 270.000, 0.900, 0 )
    set gg_dest_B003_0201 = CreateDestructable( 'B003', -4416.0, -192.0, 0.000, 0.900, 0 )
    set gg_dest_B003_1350 = CreateDestructable( 'B003', -960.0, -2240.0, 0.000, 0.900, 0 )
    set gg_dest_B003_1349 = CreateDestructable( 'B003', -4416.0, -2240.0, 0.000, 0.900, 0 )
    set gg_dest_B003_1355 = CreateDestructable( 'B003', -960.0, -64.0, 0.000, 0.900, 0 )
endfunction

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateBuildingsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'h009', -1472.0, -4032.0, 270.000 )
    set u = CreateUnit( p, 'h009', -2237.5, -3765.9, 264.614 )
    set u = CreateUnit( p, 'h009', -3385.3, -3779.2, 114.778 )
    set u = CreateUnit( p, 'h009', -3896.2, -3779.2, 64.184 )
    set u = CreateUnit( p, 'h00F', -2976.0, -4768.0, 270.000 )
    set u = CreateUnit( p, 'h009', -2496.0, -4032.0, 270.000 )
    set u = CreateUnit( p, 'h009', -4160.0, -4032.0, 270.000 )
    set u = CreateUnit( p, 'h009', -3648.0, -4032.0, 270.000 )
    set u = CreateUnit( p, 'h009', -3136.0, -4032.0, 270.000 )
    set u = CreateUnit( p, 'h008', -2816.0, -4352.0, 270.000 )
    set u = CreateUnit( p, 'h00F', -2656.0, -4768.0, 270.000 )
    set u = CreateUnit( p, 'h003', -3840.0, -4736.0, 270.000 )
    set u = CreateUnit( p, 'h003', -3328.0, -4736.0, 270.000 )
    set u = CreateUnit( p, 'h003', -2304.0, -4736.0, 270.000 )
    set u = CreateUnit( p, 'h003', -1792.0, -4736.0, 270.000 )
    set u = CreateUnit( p, 'h009', -1984.0, -4032.0, 270.000 )
    set u = CreateUnit( p, 'h009', -1726.1, -3775.7, 106.417 )
    set u = CreateUnit( p, 'n005', -10880.0, 2816.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = CreateUnit( p, 'n001', -11264.0, 2816.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set gg_unit_h000_0084 = CreateUnit( p, 'h000', -3392.0, -3136.0, 270.000 )
    set gg_unit_h000_0085 = CreateUnit( p, 'h000', -1216.0, -3136.0, 270.000 )
    set gg_unit_h00G_0096 = CreateUnit( p, 'h00G', -3904.0, -3136.0, 270.000 )
    set gg_unit_h00G_0097 = CreateUnit( p, 'h00G', -1728.0, -3136.0, 270.000 )
endfunction

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'n003', -11072.5, 2786.0, 131.060 )
    set u = CreateUnit( p, 'u000', -10255.6, -1548.2, 200.056 )
endfunction

//===========================================================================
function CreateBuildingsForPlayer1 takes nothing returns nothing
    local player p = Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'h003', -1792.0, 2304.0, 270.000 )
    set u = CreateUnit( p, 'h003', -2304.0, 2304.0, 270.000 )
    set u = CreateUnit( p, 'n001', -9792.0, 2688.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = CreateUnit( p, 'h003', -3328.0, 2304.0, 270.000 )
    set u = CreateUnit( p, 'h003', -3840.0, 2304.0, 270.000 )
    set u = CreateUnit( p, 'n005', -9408.0, 2688.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = CreateUnit( p, 'h008', -2816.0, 1792.0, 270.000 )
    set u = CreateUnit( p, 'h009', -3136.0, 1600.0, 270.000 )
    set u = CreateUnit( p, 'h009', -2496.0, 1600.0, 270.000 )
    set u = CreateUnit( p, 'h009', -1984.0, 1600.0, 270.000 )
    set u = CreateUnit( p, 'h009', -3648.0, 1600.0, 270.000 )
    set u = CreateUnit( p, 'h009', -1472.0, 1600.0, 270.000 )
    set u = CreateUnit( p, 'h009', -4160.0, 1600.0, 270.000 )
    set u = CreateUnit( p, 'h00F', -2976.0, 2336.0, 270.000 )
    set u = CreateUnit( p, 'h00F', -2656.0, 2336.0, 270.000 )
    set u = CreateUnit( p, 'h009', -3904.8, 1349.5, 157.131 )
    set u = CreateUnit( p, 'h009', -3391.8, 1349.5, 284.752 )
    set u = CreateUnit( p, 'h009', -2238.9, 1338.4, 350.727 )
    set u = CreateUnit( p, 'h009', -1725.8, 1335.3, 113.437 )
    set gg_unit_h000_0090 = CreateUnit( p, 'h000', -1856.0, 896.0, 270.000 )
    set gg_unit_h00G_0091 = CreateUnit( p, 'h00G', -1344.0, 896.0, 270.000 )
    set gg_unit_h000_0098 = CreateUnit( p, 'h000', -3328.0, 896.0, 270.000 )
    set gg_unit_h00G_0099 = CreateUnit( p, 'h00G', -3904.0, 896.0, 270.000 )
endfunction

//===========================================================================
function CreateUnitsForPlayer1 takes nothing returns nothing
    local player p = Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'n003', -9606.2, 2663.5, 51.580 )
    set u = CreateUnit( p, 'u000', -10140.4, -4095.7, 230.786 )
endfunction

//===========================================================================
function CreateBuildingsForPlayer2 takes nothing returns nothing
    local player p = Player(2)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'h008', 256.0, -1280.0, 270.000 )
    set u = CreateUnit( p, 'h009', 54.0, -968.9, 120.128 )
    set u = CreateUnit( p, 'h009', 70.4, -1612.8, 321.986 )
    set u = CreateUnit( p, 'h009', 76.2, -2111.3, 294.168 )
    set u = CreateUnit( p, 'h009', 58.1, -2618.3, 105.736 )
    set u = CreateUnit( p, 'h009', -179.2, -2381.6, 297.980 )
    set u = CreateUnit( p, 'h009', -187.6, -1855.3, 317.020 )
    set u = CreateUnit( p, 'h009', -195.3, -702.8, 241.970 )
    set u = CreateUnit( p, 'h009', 73.7, -444.7, 268.459 )
    set u = CreateUnit( p, 'h009', 71.1, 68.4, 193.431 )
    set u = CreateUnit( p, 'h009', -190.9, -189.0, 236.279 )
    set u = CreateUnit( p, 'h003', 774.2, -2308.4, 270.000 )
    set u = CreateUnit( p, 'h003', 780.9, -694.9, 270.000 )
    set u = CreateUnit( p, 'h003', 777.0, -1731.6, 270.000 )
    set u = CreateUnit( p, 'h00F', 736.0, -1376.0, 270.000 )
    set u = CreateUnit( p, 'h00F', 736.0, -1056.0, 270.000 )
    set u = CreateUnit( p, 'h003', 768.9, -270.3, 270.000 )
    set gg_unit_h000_0086 = CreateUnit( p, 'h000', -832.0, -1920.0, 270.000 )
    set gg_unit_h00G_0087 = CreateUnit( p, 'h00G', -832.0, -2496.0, 270.000 )
    set u = CreateUnit( p, 'h00G', -832.0, -320.0, 270.000 )
    set gg_unit_h000_0089 = CreateUnit( p, 'h000', -832.0, 192.0, 270.000 )
    set u = CreateUnit( p, 'n001', -8448.0, 2752.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = CreateUnit( p, 'n005', -8064.0, 2752.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
endfunction

//===========================================================================
function CreateUnitsForPlayer2 takes nothing returns nothing
    local player p = Player(2)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'n003', -8262.5, 2702.0, 131.060 )
    set u = CreateUnit( p, 'u000', -7163.9, -6629.6, 42.782 )
endfunction

//===========================================================================
function CreateBuildingsForPlayer3 takes nothing returns nothing
    local player p = Player(3)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'h008', -5888.0, -1280.0, 270.000 )
    set u = CreateUnit( p, 'h00F', -6368.0, -1440.0, 270.000 )
    set u = CreateUnit( p, 'h00F', -6368.0, -1120.0, 270.000 )
    set u = CreateUnit( p, 'h003', -6325.1, -1802.9, 270.000 )
    set u = CreateUnit( p, 'h003', -6351.6, -781.2, 270.000 )
    set u = CreateUnit( p, 'h003', -6332.3, -2311.1, 270.000 )
    set u = CreateUnit( p, 'h003', -6348.2, -262.4, 270.000 )
    set u = CreateUnit( p, 'n001', -6912.0, 2816.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = CreateUnit( p, 'n005', -6528.0, 2816.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set gg_unit_h00G_0100 = CreateUnit( p, 'h00G', -4544.0, 64.0, 270.000 )
    set gg_unit_h00G_0101 = CreateUnit( p, 'h00G', -4544.0, -2496.0, 270.000 )
    set gg_unit_h000_0102 = CreateUnit( p, 'h000', -4544.0, -1984.0, 270.000 )
    set gg_unit_h000_0103 = CreateUnit( p, 'h000', -4544.0, -448.0, 270.000 )
    set u = CreateUnit( p, 'h009', -5699.5, -966.4, 288.048 )
    set u = CreateUnit( p, 'h009', -5435.8, -693.4, 120.469 )
    set u = CreateUnit( p, 'h009', -5687.6, -445.1, 7.174 )
    set u = CreateUnit( p, 'h009', -5700.1, 70.3, 326.480 )
    set u = CreateUnit( p, 'h009', -5705.1, -1606.9, 72.270 )
    set u = CreateUnit( p, 'h009', -5701.6, -2620.4, 74.555 )
    set u = CreateUnit( p, 'h009', -5710.1, -2119.0, 114.855 )
    set u = CreateUnit( p, 'h009', -5440.5, -1864.1, 334.115 )
    set u = CreateUnit( p, 'h009', -5448.6, -2374.9, 173.864 )
    set u = CreateUnit( p, 'h009', -5446.6, -183.5, 287.653 )
endfunction

//===========================================================================
function CreateUnitsForPlayer3 takes nothing returns nothing
    local player p = Player(3)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'n003', -6715.5, 2779.7, 51.580 )
    set u = CreateUnit( p, 'u000', -10213.5, -6655.0, 209.527 )
endfunction

//===========================================================================
function CreateNeutralHostile takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'n002', -2941.3, -1141.8, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000108_DropItems )
    set u = CreateUnit( p, 'n002', -2309.1, -1146.7, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000109_DropItems )
    set u = CreateUnit( p, 'n002', -2642.5, -913.9, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000110_DropItems )
    set u = CreateUnit( p, 'n002', -2615.2, -1454.5, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000111_DropItems )
    set u = CreateUnit( p, 'n002', -3556.8, -1173.7, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000112_DropItems )
    set u = CreateUnit( p, 'n002', -2620.0, -190.9, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000113_DropItems )
    set u = CreateUnit( p, 'n002', -1522.8, -1178.6, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000114_DropItems )
    set u = CreateUnit( p, 'n002', -2587.3, -2051.9, 9.700 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000115_DropItems )
endfunction

//===========================================================================
function CreateNeutralPassive takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'u000', -8692.3, 467.7, 180.000 )
    set u = CreateUnit( p, 'u000', -8646.0, 372.3, 180.000 )
    set u = CreateUnit( p, 'u000', -8545.2, 387.3, 180.000 )
    set u = CreateUnit( p, 'u000', -8594.5, 490.7, 180.000 )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer0(  )
    call CreateBuildingsForPlayer1(  )
    call CreateBuildingsForPlayer2(  )
    call CreateBuildingsForPlayer3(  )
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
    call CreateUnitsForPlayer1(  )
    call CreateUnitsForPlayer2(  )
    call CreateUnitsForPlayer3(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings(  )
    call CreateNeutralHostile(  )
    call CreateNeutralPassive(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************

function CreateRegions takes nothing returns nothing
    local weathereffect we

    set gg_rct_Start = Rect( -10304.0, -32.0, -8608.0, 1088.0 )
    set gg_rct_Player1 = Rect( -11328.0, -2528.0, -9152.0, -640.0 )
    set gg_rct_Player2 = Rect( -11296.0, -5024.0, -9184.0, -3072.0 )
    set gg_rct_Playar3 = Rect( -11360.0, -7584.0, -9152.0, -5568.0 )
    set gg_rct_Player4 = Rect( -8256.0, -7488.0, -6080.0, -5632.0 )
    set gg_rct_Laufen2 = Rect( -9440.0, 352.0, -9376.0, 416.0 )
endfunction

//***************************************************************************
//*
//*  Cameras
//*
//***************************************************************************

function CreateCameras takes nothing returns nothing

    set gg_cam_Anfang2 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Anfang2, CAMERA_FIELD_ZOFFSET, 100.0, 0.0 )
    call CameraSetupSetField( gg_cam_Anfang2, CAMERA_FIELD_ROTATION, 12.3, 0.0 )
    call CameraSetupSetField( gg_cam_Anfang2, CAMERA_FIELD_ANGLE_OF_ATTACK, 326.2, 0.0 )
    call CameraSetupSetField( gg_cam_Anfang2, CAMERA_FIELD_TARGET_DISTANCE, 769.7, 0.0 )
    call CameraSetupSetField( gg_cam_Anfang2, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Anfang2, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Anfang2, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Anfang2, -9402.9, 385.9, 0.0 )

    set gg_cam_Player1 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Player1, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player1, CAMERA_FIELD_ROTATION, 93.5, 0.0 )
    call CameraSetupSetField( gg_cam_Player1, CAMERA_FIELD_ANGLE_OF_ATTACK, 297.6, 0.0 )
    call CameraSetupSetField( gg_cam_Player1, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player1, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player1, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player1, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Player1, -10149.3, -1459.4, 0.0 )

    set gg_cam_Player2 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Player2, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player2, CAMERA_FIELD_ROTATION, 93.5, 0.0 )
    call CameraSetupSetField( gg_cam_Player2, CAMERA_FIELD_ANGLE_OF_ATTACK, 297.6, 0.0 )
    call CameraSetupSetField( gg_cam_Player2, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player2, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player2, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player2, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Player2, -10114.3, -4086.3, 0.0 )

    set gg_cam_Player3 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Player3, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player3, CAMERA_FIELD_ROTATION, 93.5, 0.0 )
    call CameraSetupSetField( gg_cam_Player3, CAMERA_FIELD_ANGLE_OF_ATTACK, 297.6, 0.0 )
    call CameraSetupSetField( gg_cam_Player3, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player3, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player3, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player3, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Player3, -10234.1, -6675.4, 0.0 )

    set gg_cam_Player4 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Player4, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player4, CAMERA_FIELD_ROTATION, 93.5, 0.0 )
    call CameraSetupSetField( gg_cam_Player4, CAMERA_FIELD_ANGLE_OF_ATTACK, 297.6, 0.0 )
    call CameraSetupSetField( gg_cam_Player4, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player4, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player4, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Player4, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Player4, -7170.4, -6664.8, 0.0 )

endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: SpielerGruppe
//===========================================================================
function Trig_SpielerGruppe_Actions takes nothing returns nothing
    call MeleeStartingHeroLimit(  )
    call MeleeStartingAI(  )
    call ForceAddPlayerSimple( Player(0), udg_Spieler1 )
    call ForceAddPlayerSimple( Player(1), udg_Spieler2 )
    call ForceAddPlayerSimple( Player(2), udg_Spieler3 )
    call ForceAddPlayerSimple( Player(3), udg_Spieler4 )
endfunction

//===========================================================================
function InitTrig_SpielerGruppe takes nothing returns nothing
    set gg_trg_SpielerGruppe = CreateTrigger(  )
    call TriggerAddAction( gg_trg_SpielerGruppe, function Trig_SpielerGruppe_Actions )
endfunction

//===========================================================================
// Trigger: Musik
//===========================================================================
function Trig_Musik_Actions takes nothing returns nothing
    call PlayThematicMusicBJ( "Dota - 2.mp3" )
endfunction

//===========================================================================
function InitTrig_Musik takes nothing returns nothing
    set gg_trg_Musik = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Musik, 0.00 )
    call TriggerAddAction( gg_trg_Musik, function Trig_Musik_Actions )
endfunction

//===========================================================================
// Trigger: Verkaufen
//===========================================================================
function Trig_Verkaufen_Conditions takes nothing returns boolean
    if ( not ( 'A00F' == GetSpellAbilityId() ) ) then
        return false
    endif
    return true
endfunction

function Trig_Verkaufen_Actions takes nothing returns nothing
    call CreateNUnitsAtLocFacingLocBJ( 1, 'e000', Player(PLAYER_NEUTRAL_PASSIVE), GetUnitLoc(GetTriggerUnit()), GetUnitLoc(GetTriggerUnit()) )
    call UnitApplyTimedLifeBJ( 2.00, 'BTLF', GetLastCreatedUnit() )
    call RemoveUnit( GetTriggerUnit() )
endfunction

//===========================================================================
function InitTrig_Verkaufen takes nothing returns nothing
    set gg_trg_Verkaufen = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Verkaufen, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Verkaufen, Condition( function Trig_Verkaufen_Conditions ) )
    call TriggerAddAction( gg_trg_Verkaufen, function Trig_Verkaufen_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player1 1
//===========================================================================
function Trig_Gate_Open_player1_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0096 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player1_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B002_0198 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player1_1 takes nothing returns nothing
    set gg_trg_Gate_Open_player1_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player1_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player1_1, Condition( function Trig_Gate_Open_player1_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player1_1, function Trig_Gate_Open_player1_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player1 1
//===========================================================================
function Trig_Gate_Close_player1_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0084 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player1_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B002_0198 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player1_1 takes nothing returns nothing
    set gg_trg_Gate_Close_player1_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player1_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player1_1, Condition( function Trig_Gate_Close_player1_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player1_1, function Trig_Gate_Close_player1_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player1 2
//===========================================================================
function Trig_Gate_Open_player1_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0097 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player1_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B002_0200 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player1_2 takes nothing returns nothing
    set gg_trg_Gate_Open_player1_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player1_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player1_2, Condition( function Trig_Gate_Open_player1_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player1_2, function Trig_Gate_Open_player1_2_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player1 2
//===========================================================================
function Trig_Gate_Close_player1_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0085 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player1_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B002_0200 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player1_2 takes nothing returns nothing
    set gg_trg_Gate_Close_player1_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player1_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player1_2, Condition( function Trig_Gate_Close_player1_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player1_2, function Trig_Gate_Close_player1_2_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player2 1
//===========================================================================
function Trig_Gate_Open_player2_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0091 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player2_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B002_0187 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player2_1 takes nothing returns nothing
    set gg_trg_Gate_Open_player2_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player2_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player2_1, Condition( function Trig_Gate_Open_player2_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player2_1, function Trig_Gate_Open_player2_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player2 1
//===========================================================================
function Trig_Gate_Close_player2_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0090 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player2_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B002_0187 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player2_1 takes nothing returns nothing
    set gg_trg_Gate_Close_player2_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player2_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player2_1, Condition( function Trig_Gate_Close_player2_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player2_1, function Trig_Gate_Close_player2_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player2 2
//===========================================================================
function Trig_Gate_Open_player2_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0099 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player2_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B002_0188 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player2_2 takes nothing returns nothing
    set gg_trg_Gate_Open_player2_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player2_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player2_2, Condition( function Trig_Gate_Open_player2_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player2_2, function Trig_Gate_Open_player2_2_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player2 2
//===========================================================================
function Trig_Gate_Close_player2_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0098 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player2_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B002_0188 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player2_2 takes nothing returns nothing
    set gg_trg_Gate_Close_player2_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player2_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player2_2, Condition( function Trig_Gate_Close_player2_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player2_2, function Trig_Gate_Close_player2_2_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player3 1
//===========================================================================
function Trig_Gate_Open_player3_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0101 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player3_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B003_1349 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player3_1 takes nothing returns nothing
    set gg_trg_Gate_Open_player3_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player3_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player3_1, Condition( function Trig_Gate_Open_player3_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player3_1, function Trig_Gate_Open_player3_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player3 1
//===========================================================================
function Trig_Gate_Close_player3_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0102 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player3_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B003_1349 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player3_1 takes nothing returns nothing
    set gg_trg_Gate_Close_player3_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player3_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player3_1, Condition( function Trig_Gate_Close_player3_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player3_1, function Trig_Gate_Close_player3_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player3 2
//===========================================================================
function Trig_Gate_Open_player3_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0100 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player3_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B003_0201 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player3_2 takes nothing returns nothing
    set gg_trg_Gate_Open_player3_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player3_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player3_2, Condition( function Trig_Gate_Open_player3_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player3_2, function Trig_Gate_Open_player3_2_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player3 2
//===========================================================================
function Trig_Gate_Close_player3_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0103 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player3_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B003_0201 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player3_2 takes nothing returns nothing
    set gg_trg_Gate_Close_player3_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player3_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player3_2, Condition( function Trig_Gate_Close_player3_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player3_2, function Trig_Gate_Close_player3_2_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player4 1
//===========================================================================
function Trig_Gate_Open_player4_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0087 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player4_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B003_1350 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player4_1 takes nothing returns nothing
    set gg_trg_Gate_Open_player4_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player4_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player4_1, Condition( function Trig_Gate_Open_player4_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player4_1, function Trig_Gate_Open_player4_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player4 1
//===========================================================================
function Trig_Gate_Close_player4_1_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0086 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player4_1_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B003_1350 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player4_1 takes nothing returns nothing
    set gg_trg_Gate_Close_player4_1 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player4_1, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player4_1, Condition( function Trig_Gate_Close_player4_1_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player4_1, function Trig_Gate_Close_player4_1_Actions )
endfunction

//===========================================================================
// Trigger: Gate Open player4 2
//===========================================================================
function Trig_Gate_Open_player4_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h00G_0087 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Open_player4_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_OPEN, gg_dest_B003_1355 )
endfunction

//===========================================================================
function InitTrig_Gate_Open_player4_2 takes nothing returns nothing
    set gg_trg_Gate_Open_player4_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Open_player4_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Open_player4_2, Condition( function Trig_Gate_Open_player4_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Open_player4_2, function Trig_Gate_Open_player4_2_Actions )
endfunction

//===========================================================================
// Trigger: Gate Close player4 2
//===========================================================================
function Trig_Gate_Close_player4_2_Conditions takes nothing returns boolean
    if ( not ( GetTriggerUnit() == gg_unit_h000_0089 ) ) then
        return false
    endif
    if ( not ( GetSpellAbilityId() == 'A00M' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Gate_Close_player4_2_Actions takes nothing returns nothing
    call ModifyGateBJ( bj_GATEOPERATION_CLOSE, gg_dest_B003_1355 )
endfunction

//===========================================================================
function InitTrig_Gate_Close_player4_2 takes nothing returns nothing
    set gg_trg_Gate_Close_player4_2 = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Gate_Close_player4_2, EVENT_PLAYER_UNIT_SPELL_CHANNEL )
    call TriggerAddCondition( gg_trg_Gate_Close_player4_2, Condition( function Trig_Gate_Close_player4_2_Conditions ) )
    call TriggerAddAction( gg_trg_Gate_Close_player4_2, function Trig_Gate_Close_player4_2_Actions )
endfunction

//===========================================================================
// Trigger: StartGeld
//===========================================================================
function Trig_StartGeld_Func001002 takes nothing returns nothing
    call AdjustPlayerStateBJ( 100, GetEnumPlayer(), PLAYER_STATE_RESOURCE_LUMBER )
endfunction

function Trig_StartGeld_Func002002 takes nothing returns nothing
    call AdjustPlayerStateBJ( 100, GetEnumPlayer(), PLAYER_STATE_RESOURCE_GOLD )
endfunction

function Trig_StartGeld_Actions takes nothing returns nothing
    call ForForce( GetPlayersAll(), function Trig_StartGeld_Func001002 )
    call ForForce( GetPlayersAll(), function Trig_StartGeld_Func002002 )
endfunction

//===========================================================================
function InitTrig_StartGeld takes nothing returns nothing
    set gg_trg_StartGeld = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_StartGeld, 1.00 )
    call TriggerAddAction( gg_trg_StartGeld, function Trig_StartGeld_Actions )
endfunction

//===========================================================================
// Trigger: Pause
//===========================================================================
function Trig_Pause_Actions takes nothing returns nothing
    call PauseGameOn(  )
endfunction

//===========================================================================
function InitTrig_Pause takes nothing returns nothing
    set gg_trg_Pause = CreateTrigger(  )
    call TriggerRegisterPlayerChatEvent( gg_trg_Pause, Player(0), "-pause", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_Pause, Player(1), "-pause", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_Pause, Player(2), "-pause", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_Pause, Player(3), "-pause", true )
    call TriggerAddAction( gg_trg_Pause, function Trig_Pause_Actions )
endfunction

//===========================================================================
// Trigger: Unpause
//===========================================================================
function Trig_Unpause_Actions takes nothing returns nothing
    call PauseGameOff(  )
endfunction

//===========================================================================
function InitTrig_Unpause takes nothing returns nothing
    set gg_trg_Unpause = CreateTrigger(  )
    call TriggerRegisterPlayerChatEvent( gg_trg_Unpause, Player(0), "-unpause", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_Unpause, Player(1), "-unpause", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_Unpause, Player(2), "-unpause", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_Unpause, Player(3), "-unpause", true )
    call TriggerAddAction( gg_trg_Unpause, function Trig_Unpause_Actions )
endfunction

//===========================================================================
// Trigger: AdminComand
//===========================================================================
function Trig_AdminComand_Actions takes nothing returns nothing
    call AdjustPlayerStateBJ( 1000000, GetEnumPlayer(), PLAYER_STATE_RESOURCE_GOLD )
endfunction

//===========================================================================
function InitTrig_AdminComand takes nothing returns nothing
    set gg_trg_AdminComand = CreateTrigger(  )
    call TriggerRegisterPlayerChatEvent( gg_trg_AdminComand, Player(0), "-Gold", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_AdminComand, Player(1), "-Gold", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_AdminComand, Player(2), "-Gold", true )
    call TriggerRegisterPlayerChatEvent( gg_trg_AdminComand, Player(3), "-Gold", true )
    call TriggerAddAction( gg_trg_AdminComand, function Trig_AdminComand_Actions )
endfunction

//===========================================================================
// Trigger: GeldBeute
//===========================================================================
function Trig_GeldBeute_Actions takes nothing returns nothing
    call SetPlayerFlagBJ( PLAYER_STATE_GIVES_BOUNTY, true, Player(0) )
    call SetPlayerFlagBJ( PLAYER_STATE_GIVES_BOUNTY, true, Player(1) )
    call SetPlayerFlagBJ( PLAYER_STATE_GIVES_BOUNTY, true, Player(2) )
    call SetPlayerFlagBJ( PLAYER_STATE_GIVES_BOUNTY, true, Player(3) )
endfunction

//===========================================================================
function InitTrig_GeldBeute takes nothing returns nothing
    set gg_trg_GeldBeute = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_GeldBeute, 1.00 )
    call TriggerAddAction( gg_trg_GeldBeute, function Trig_GeldBeute_Actions )
endfunction

//===========================================================================
// Trigger: Building Destroyed
//===========================================================================
function Trig_Building_Destroyed_Func004C takes nothing returns boolean
    if ( ( GetUnitTypeId(GetTriggerUnit()) == 'h008' ) ) then
        return true
    endif
    return false
endfunction

function Trig_Building_Destroyed_Conditions takes nothing returns boolean
    if ( not Trig_Building_Destroyed_Func004C() ) then
        return false
    endif
    return true
endfunction

function Trig_Building_Destroyed_Func002002 takes nothing returns nothing
    call KillUnit( GetEnumUnit() )
endfunction

function Trig_Building_Destroyed_Actions takes nothing returns nothing
    call DisplayTextToForce( GetPlayersAll(), ( GetPlayerName(GetOwningPlayer(GetTriggerUnit())) + "|cffff0000 has been defeated!!|r" ) )
    call ForGroupBJ( GetUnitsOfPlayerAll(GetOwningPlayer(GetTriggerUnit())), function Trig_Building_Destroyed_Func002002 )
    call ForceRemovePlayerSimple( GetOwningPlayer(GetTriggerUnit()), GetPlayersAll() )
endfunction

//===========================================================================
function InitTrig_Building_Destroyed takes nothing returns nothing
    set gg_trg_Building_Destroyed = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Building_Destroyed, EVENT_PLAYER_UNIT_DEATH )
    call TriggerAddCondition( gg_trg_Building_Destroyed, Condition( function Trig_Building_Destroyed_Conditions ) )
    call TriggerAddAction( gg_trg_Building_Destroyed, function Trig_Building_Destroyed_Actions )
endfunction

//===========================================================================
// Trigger: Check if Players Leave
//===========================================================================
function Trig_Check_if_Players_Leave_Func002Func001Func002002 takes nothing returns nothing
    call KillUnit( GetEnumUnit() )
endfunction

function Trig_Check_if_Players_Leave_Func002Func001C takes nothing returns boolean
    if ( not ( GetPlayerSlotState(GetEnumPlayer()) != PLAYER_SLOT_STATE_PLAYING ) ) then
        return false
    endif
    return true
endfunction

function Trig_Check_if_Players_Leave_Func002A takes nothing returns nothing
    if ( Trig_Check_if_Players_Leave_Func002Func001C() ) then
        call ForGroupBJ( GetUnitsOfPlayerAll(GetEnumPlayer()), function Trig_Check_if_Players_Leave_Func002Func001Func002002 )
        call DisplayTextToForce( GetPlayersAll(), ( GetPlayerName(GetEnumPlayer()) + " has left the game." ) )
        call ForceRemovePlayerSimple( GetEnumPlayer(), GetPlayersAll() )
    else
        call DoNothing(  )
    endif
endfunction

function Trig_Check_if_Players_Leave_Actions takes nothing returns nothing
    call ForForce( GetPlayersAll(), function Trig_Check_if_Players_Leave_Func002A )
endfunction

//===========================================================================
function InitTrig_Check_if_Players_Leave takes nothing returns nothing
    set gg_trg_Check_if_Players_Leave = CreateTrigger(  )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Check_if_Players_Leave, 1.00 )
    call TriggerAddAction( gg_trg_Check_if_Players_Leave, function Trig_Check_if_Players_Leave_Actions )
endfunction

//===========================================================================
// Trigger: Check if Players is not in use
//===========================================================================
function Trig_Check_if_Players_is_not_in_use_Func002Func001Func002002 takes nothing returns nothing
    call KillUnit( GetEnumUnit() )
endfunction

function Trig_Check_if_Players_is_not_in_use_Func002Func001C takes nothing returns boolean
    if ( not ( GetPlayerSlotState(GetEnumPlayer()) == PLAYER_SLOT_STATE_EMPTY ) ) then
        return false
    endif
    return true
endfunction

function Trig_Check_if_Players_is_not_in_use_Func002A takes nothing returns nothing
    if ( Trig_Check_if_Players_is_not_in_use_Func002Func001C() ) then
        call ForGroupBJ( GetUnitsOfPlayerAll(GetEnumPlayer()), function Trig_Check_if_Players_is_not_in_use_Func002Func001Func002002 )
        call ForceRemovePlayerSimple( GetEnumPlayer(), GetPlayersAll() )
    else
        call DoNothing(  )
    endif
endfunction

function Trig_Check_if_Players_is_not_in_use_Actions takes nothing returns nothing
    call ForForce( GetPlayersAll(), function Trig_Check_if_Players_is_not_in_use_Func002A )
endfunction

//===========================================================================
function InitTrig_Check_if_Players_is_not_in_use takes nothing returns nothing
    set gg_trg_Check_if_Players_is_not_in_use = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Check_if_Players_is_not_in_use, function Trig_Check_if_Players_is_not_in_use_Actions )
endfunction

//===========================================================================
// Trigger: Sichtbar
//===========================================================================
function Trig_Sichtbar_Actions takes nothing returns nothing
    call CreateFogModifierRectBJ( true, Player(0), FOG_OF_WAR_VISIBLE, gg_rct_Start )
    call CreateFogModifierRectBJ( true, Player(0), FOG_OF_WAR_VISIBLE, gg_rct_Player1 )
    call CreateFogModifierRectBJ( true, Player(1), FOG_OF_WAR_VISIBLE, gg_rct_Start )
    call CreateFogModifierRectBJ( true, Player(1), FOG_OF_WAR_VISIBLE, gg_rct_Player2 )
    call CreateFogModifierRectBJ( true, Player(2), FOG_OF_WAR_VISIBLE, gg_rct_Start )
    call CreateFogModifierRectBJ( true, Player(2), FOG_OF_WAR_VISIBLE, gg_rct_Playar3 )
    call CreateFogModifierRectBJ( true, Player(3), FOG_OF_WAR_VISIBLE, gg_rct_Start )
    call CreateFogModifierRectBJ( true, Player(3), FOG_OF_WAR_VISIBLE, gg_rct_Player4 )
endfunction

//===========================================================================
function InitTrig_Sichtbar takes nothing returns nothing
    set gg_trg_Sichtbar = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Sichtbar, function Trig_Sichtbar_Actions )
endfunction

//===========================================================================
// Trigger: Winners Declared
//===========================================================================
function Trig_Winners_Declared_Func002C takes nothing returns boolean
    if ( not ( IsPlayerInForce(Player(1), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(2), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(3), GetPlayersAll()) == false ) ) then
        return false
    endif
    return true
endfunction

function Trig_Winners_Declared_Func003C takes nothing returns boolean
    if ( not ( IsPlayerInForce(Player(0), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(2), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(3), GetPlayersAll()) == false ) ) then
        return false
    endif
    return true
endfunction

function Trig_Winners_Declared_Func004C takes nothing returns boolean
    if ( not ( IsPlayerInForce(Player(0), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(1), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(3), GetPlayersAll()) == false ) ) then
        return false
    endif
    return true
endfunction

function Trig_Winners_Declared_Func005C takes nothing returns boolean
    if ( not ( IsPlayerInForce(Player(0), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(1), GetPlayersAll()) == false ) ) then
        return false
    endif
    if ( not ( IsPlayerInForce(Player(2), GetPlayersAll()) == false ) ) then
        return false
    endif
    return true
endfunction

function Trig_Winners_Declared_Actions takes nothing returns nothing
    if ( Trig_Winners_Declared_Func002C() ) then
        call CustomVictoryBJ( Player(0), true, true )
    else
        call DoNothing(  )
    endif
    if ( Trig_Winners_Declared_Func003C() ) then
        call CustomVictoryBJ( Player(1), true, true )
    else
        call DoNothing(  )
    endif
    if ( Trig_Winners_Declared_Func004C() ) then
        call CustomVictoryBJ( Player(2), true, true )
    else
        call DoNothing(  )
    endif
    if ( Trig_Winners_Declared_Func005C() ) then
        call CustomVictoryBJ( Player(3), true, true )
    else
        call DoNothing(  )
    endif
endfunction

//===========================================================================
function InitTrig_Winners_Declared takes nothing returns nothing
    set gg_trg_Winners_Declared = CreateTrigger(  )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Winners_Declared, 5.00 )
    call TriggerAddAction( gg_trg_Winners_Declared, function Trig_Winners_Declared_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_SpielerGruppe(  )
    call InitTrig_Musik(  )
    call InitTrig_Verkaufen(  )
    call InitTrig_Gate_Open_player1_1(  )
    call InitTrig_Gate_Close_player1_1(  )
    call InitTrig_Gate_Open_player1_2(  )
    call InitTrig_Gate_Close_player1_2(  )
    call InitTrig_Gate_Open_player2_1(  )
    call InitTrig_Gate_Close_player2_1(  )
    call InitTrig_Gate_Open_player2_2(  )
    call InitTrig_Gate_Close_player2_2(  )
    call InitTrig_Gate_Open_player3_1(  )
    call InitTrig_Gate_Close_player3_1(  )
    call InitTrig_Gate_Open_player3_2(  )
    call InitTrig_Gate_Close_player3_2(  )
    call InitTrig_Gate_Open_player4_1(  )
    call InitTrig_Gate_Close_player4_1(  )
    call InitTrig_Gate_Open_player4_2(  )
    call InitTrig_Gate_Close_player4_2(  )
    call InitTrig_StartGeld(  )
    call InitTrig_Pause(  )
    call InitTrig_Unpause(  )
    call InitTrig_AdminComand(  )
    call InitTrig_GeldBeute(  )
    call InitTrig_Building_Destroyed(  )
    call InitTrig_Check_if_Players_Leave(  )
    call InitTrig_Check_if_Players_is_not_in_use(  )
    call InitTrig_Sichtbar(  )
    call InitTrig_Winners_Declared(  )
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute( gg_trg_SpielerGruppe )
    call ConditionalTriggerExecute( gg_trg_Check_if_Players_is_not_in_use )
    call ConditionalTriggerExecute( gg_trg_Sichtbar )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(0), true )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(1), true )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )

    // Player 2
    call SetPlayerStartLocation( Player(2), 2 )
    call ForcePlayerStartLocation( Player(2), 2 )
    call SetPlayerColor( Player(2), ConvertPlayerColor(2) )
    call SetPlayerRacePreference( Player(2), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(2), true )
    call SetPlayerController( Player(2), MAP_CONTROL_USER )

    // Player 3
    call SetPlayerStartLocation( Player(3), 3 )
    call ForcePlayerStartLocation( Player(3), 3 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(3), true )
    call SetPlayerController( Player(3), MAP_CONTROL_USER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerTeam( Player(1), 0 )
    call SetPlayerTeam( Player(2), 0 )
    call SetPlayerTeam( Player(3), 0 )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 0, 1 )
    call SetStartLocPrio( 0, 0, 1, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 1, 2 )
    call SetStartLocPrio( 1, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 1, 3, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 2, 2 )
    call SetStartLocPrio( 2, 0, 1, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 2, 1, 3, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 3, 2 )
    call SetStartLocPrio( 3, 0, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 1, 2, MAP_LOC_PRIO_HIGH )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -12160.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -8192.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 2560.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3456.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -12160.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3456.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 2560.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -8192.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "LordaeronSummerDay" )
    call SetAmbientNightSound( "LordaeronSummerNight" )
    call SetMapMusic( "Music", true, 0 )
    call InitSounds(  )
    call CreateRegions(  )
    call CreateCameras(  )
    call CreateAllDestructables(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )
    call RunInitializationTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_007" )
    call SetMapDescription( "TRIGSTR_009" )
    call SetPlayers( 4 )
    call SetTeams( 4 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )

    call DefineStartLocation( 0, -10240.0, -1536.0 )
    call DefineStartLocation( 1, -10112.0, -4096.0 )
    call DefineStartLocation( 2, -7168.0, -6656.0 )
    call DefineStartLocation( 3, -10240.0, -6656.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call SetPlayerSlotAvailable( Player(0), MAP_CONTROL_USER )
    call SetPlayerSlotAvailable( Player(1), MAP_CONTROL_USER )
    call SetPlayerSlotAvailable( Player(2), MAP_CONTROL_USER )
    call SetPlayerSlotAvailable( Player(3), MAP_CONTROL_USER )
    call InitGenericPlayerSlots(  )
    call InitAllyPriorities(  )
endfunction

